/* ==========================================================================
   MCMI-IV — Banco de ítems (adaptación española, Pearson 2018)
   Fuente: Manual MCMI-IV, Anexo A «Ítems» + Cuadernillo.
   195 ítems, formato Verdadero / Falso.
   ========================================================================== */
(function (global) {
  'use strict';

  var ITEMS = [
    'Últimamente parece que me quedo sin fuerzas, incluso por la mañana.',
    'Siempre me aseguro de que mi trabajo esté bien planeado y organizado.',
    'Disfruto haciendo tantas cosas diferentes que no puedo decidir por cuál empezar.',
    'Me preocupa que las personas de las que dependo me abandonen.',
    'Aunque me da miedo hacer amistades, me gustaría tener más de las que tengo.',
    'Raramente exteriorizo los pocos sentimientos que tengo.',
    'Me cuesta mantener el equilibrio cuando camino.',
    'Siempre busco oportunidades nuevas que me resulten emocionantes.',
    'Algunas veces puedo ser bastante duro y desagradable con mi familia.',
    'Me gusta ser el centro de atención.',
    'De adolescente tuve muchos problemas por mi mal comportamiento en la escuela o instituto.',
    'Me da miedo hacerme muy amigo de alguien porque podría acabar sintiéndome ridiculizado o avergonzado.',
    'Noto que la gente está hablando de mí cuando paso a su lado.',
    'Hace unos años comencé a sentirme un fracasado.',
    'Si puedo elegir, prefiero hacer las cosas solo.',
    'Últimamente he comenzado a sentir deseos de destrozar cosas.',
    'Las cosas que hoy van bien no durarán mucho tiempo.',
    'A veces, cuando las cosas empiezan a irme mal, me siento como si estuviera loco o fuera de la realidad.',
    'Hago lo que quiero sin preocuparme de las consecuencias que tenga en los demás.',
    'Afronto mis actividades diarias con mucha energía y persistencia.',
    'Nunca perdono una ofensa ni olvido una situación embarazosa que alguien me haya causado.',
    'Me siento extremadamente deprimido y triste gran parte del tiempo.',
    'Siempre tiendo a culparme cuando las cosas van mal.',
    'Hace mucho tiempo decidí que es mejor tener poca relación con la gente.',
    'Tengo un problema con el alcohol que nos ha creado dificultades a mí y a mi familia.',
    'Soy una persona socialmente muy reservada y tímida.',
    'Muchas veces me siento muy alegre y animado sin ninguna razón.',
    'En las últimas semanas me he sentido agotado sin ningún motivo en particular.',
    'Mi tiempo es más valioso que el de los demás.',
    'Siempre estoy buscando hacer nuevas amistades y conocer gente nueva.',
    'Desde hace unas semanas estoy muy nervioso.',
    'Simplemente, no he tenido la suerte que otras personas han tenido en la vida.',
    'Las ideas me dan vueltas en la cabeza una y otra vez y no desaparecen.',
    'Desde hace uno o dos años, al pensar sobre la vida, me siento muy triste y desanimado.',
    'Intento hacerlo todo tan perfecto como sea posible.',
    'Mi adicción a las drogas hizo que faltara al trabajo.',
    'Mi estado de ánimo varía mucho de un día para otro.',
    'Utilizo mi encanto para conseguir lo que quiero.',
    'A menudo pienso que no merezco las cosas buenas que me pasan.',
    'En el pasado me corté o autolesioné a propósito.',
    'Tengo la sensación de que no duermo, y me levanto tan cansado como al acostarme.',
    'A menudo dejo que los demás tomen por mí decisiones importantes.',
    'Parece que pocas cosas me entristecen o me alegran.',
    'A menudo tengo pensamientos extraños de los que desearía librarme.',
    'Tengo muchos problemas para controlar el impulso de beber alcohol en exceso.',
    'Hago amistades con mucha más facilidad que la mayoría de la gente que conozco.',
    'Me da vergüenza el maltrato que sufrí cuando era joven.',
    'Me parece muy bien que haya normas porque son una buena guía a seguir.',
    'El año pasado aparecí en la portada de varias revistas.',
    'A menudo me enfado con la gente que hace las cosas lentamente.',
    'Me paso la vida preocupándome por una cosa u otra.',
    'Siempre me pregunto cuál es la razón real de que alguien sea especialmente agradable conmigo.',
    'Mis actividades cotidianas me animan y motivan.',
    'Tengo muchas ideas que son avanzadas para los tiempos actuales.',
    'Desde que sufrí una conmoción cerebral grave, ya no puedo concentrarme en nada.',
    'Antes la gente decía que me interesaba y me entusiasmaba demasiado por muchas cosas.',
    'He perdido el apetito por completo, y la mayoría de las noches tengo problemas para dormir.',
    'Desde que era niño he ido perdiendo contacto con la realidad.',
    'No puedo sentir mucho placer porque no creo que lo merezca.',
    'Prefiero que me digan lo que tengo que hacer en lugar de decidir por mí mismo.',
    'Consumir drogas me ha causado discusiones con mi familia.',
    'El recuerdo de una experiencia muy perturbadora sigue presente en mis pensamientos y me obsesiona.',
    'La mayoría de la gente me considera una persona prudente y cuidadosa.',
    'Parece que he perdido el interés en la mayoría de las cosas que solía encontrar placenteras, como el sexo.',
    'He tenido problemas con la ley un par de veces.',
    'He tenido que ser muy duro con algunas personas para mantenerlas a raya.',
    'Estoy muy seguro de mí mismo.',
    'La gente intenta hacerme creer que estoy loco.',
    'Me doy atracones de comida un par de veces a la semana.',
    'Frecuentemente siento que no hay nada dentro de mí, como si estuviera vacío y hueco.',
    'Siempre me ha resultado difícil dejar de sentirme deprimido y triste.',
    'Cuando estoy solo y lejos de casa, a menudo comienzo a sentirme tenso y entro en pánico.',
    'La gente dice que soy una persona formal y con valores morales.',
    'Me cuesta controlar mi ira.',
    'Soy una persona muy optimista.',
    'Años después, aún tengo pesadillas sobre un hecho que fue una amenaza real para mi vida.',
    'Me parece que necesito que alguien me oriente para hacer las cosas.',
    'Recientemente he pensado muy en serio en quitarme la vida.',
    'Hay mala gente que intenta llevarse el mérito de lo que he hecho o pensado.',
    'Últimamente estoy destrozado.',
    'Consumir drogas puede ser irresponsable, pero en el pasado las he necesitado.',
    'Soy una persona muy variable, cambio de opinión y sentimientos continuamente.',
    'Se me da muy bien inventar excusas cuando me meto en problemas.',
    'Cuando estoy en una fiesta, nunca me aíslo de los demás.',
    'Parece que echo a perder las buenas oportunidades que se cruzan en mi camino.',
    'Algunas veces me provoco el vómito después de comer.',
    'Soy una persona especial, así que no me importa lo que piensen los demás.',
    'Observo atentamente a mi familia para saber en quién se puede confiar y en quién no.',
    'Ciertos pensamientos vuelven a mi mente una y otra vez.',
    'Pocas cosas en la vida me resultan placenteras.',
    'Me siento agitado y me cuesta conciliar el sueño porque tengo recuerdos dolorosos dando vueltas en mi cabeza.',
    'A menudo me pierdo en mis pensamientos y me olvido de lo que está pasando a mi alrededor.',
    'Nunca he podido dejar de sentir que no valgo nada para los demás.',
    'Tengo un problema con la bebida que he tratado de solucionar sin éxito.',
    'Alguien ha estado intentando controlar mi mente.',
    'La mayoría de las personas que han triunfado han tenido suerte o han sido deshonestas.',
    'A menudo irrito a la gente dándoles órdenes.',
    'No he visto un coche en los últimos diez años.',
    'Siempre me siento cohibido y tenso en las reuniones sociales.',
    'Creo que provoco situaciones en las que resulto herido o me siento rechazado.',
    'Me siento profundamente deprimido sin saber por qué.',
    'La gente dice que soy una persona delgada, pero creo que mis muslos y mi trasero son demasiado grandes.',
    'A menudo disfruto provocando una discusión o una pelea.',
    'Tengo mucho cuidado en mantener mi vida como algo privado, para que nadie pueda aprovecharse de mí.',
    'El consumo de drogas me ha causado muchos problemas.',
    'A menudo me echan la culpa por cosas de las que no soy responsable.',
    'Pensar en el futuro al comienzo de cada día me hace sentir extremadamente deprimido.',
    'A veces las personas se molestan conmigo porque dicen que hablo mucho o demasiado deprisa.',
    'Yo nunca podría arreglármelas solo.',
    'Mi cabeza no funciona bien desde que hace unos años tuve una lesión cerebral.',
    'Me siento solo y vacío la mayor parte del tiempo.',
    'La gente se burla de mí a mis espaldas.',
    'Últimamente sudo mucho y me siento muy tenso.',
    'Estas últimas semanas me he sentido cada vez más triste.',
    'Me enfurezco rápidamente con la gente que me molesta.',
    'A veces no he podido pasar el día sin tomar drogas.',
    'Me gusta mucho coquetear.',
    'Ya no tengo energía para concentrarme en mis responsabilidades diarias.',
    'Mis emociones no parecen ser tan intensas como las del resto de la gente.',
    'Me siento débil y cansado la mayor parte del tiempo.',
    'Ideas extrañas entran en mi mente, dan vueltas y vueltas en mi cabeza, y no desaparecen.',
    'Los demás tienen oportunidades que yo no tengo.',
    'Repito ciertos comportamientos una y otra vez, algunas veces para reducir mi ansiedad y otras para evitar que pase algo malo.',
    'He tomado medicación que no me habían recetado.',
    'Mi vida actual todavía se ve afectada por recuerdos e imágenes de algo terrible que me pasó.',
    'A menudo echo a perder las cosas buenas que me ocurren.',
    'Voces malvadas intentan apoderarse de mi mente.',
    'Me siento muy culpable cuando pierdo el control.',
    'Mi entusiasmo por el trabajo que hago nunca disminuye.',
    'Supongo que no soy diferente de mis padres ya que, en cierto modo, me he convertido en un alcohólico.',
    'Últimamente tengo que pensar las cosas una y otra vez sin ningún motivo.',
    'Animo a los demás a que admiren lo que digo o hago.',
    'Dejo de hacer cosas si tengo que hacerlas solo.',
    'He intentado suicidarme.',
    'Soy una persona miedosa y reservada.',
    'A las personas que supuestamente son mis amigos les gustaría hacerme daño.',
    'A menudo me dejo llevar por la rabia y luego me siento muy culpable.',
    'A menudo oigo cosas con tanta claridad que me molesta.',
    'Aparte de mi familia, tengo muy pocos amigos íntimos.',
    'La desorganización me hace sentir muy incómodo.',
    'A menudo critico mucho a la gente que me irrita.',
    'Tengo muchas cualidades que los demás querrían tener.',
    'Terribles acontecimientos de mi pasado reaparecen obsesivamente en mis pensamientos y sueños.',
    'Sé que he gastado más dinero en droga del que debería.',
    'A menudo, y antes de darme cuenta, me pongo a gritar enfadado a mis amigos y familiares.',
    'Me preocupa que mi cuerpo se desgaste rápidamente.',
    'Está bien burlar la ley si es poco probable que te atrapen.',
    'Creo que hay una conspiración contra mí.',
    'Soy una persona solitaria y no me molesta.',
    'Todavía me aterrorizo cuando pienso en una experiencia traumática que tuve hace años.',
    'Últimamente me he sentido muy culpable porque ya no soy capaz de hacer nada bien.',
    'Los castigos nunca me impidieron hacer lo que quería.',
    'Pocas veces creo lo que la gente me dice.',
    'Soy una persona muy sociable y extrovertida.',
    'Me entusiasmo con casi todo lo que hago.',
    'Estoy confundido sobre quién soy.',
    'Odio pensar en el maltrato que sufrí en la infancia.',
    'Nunca infringiría la ley, aunque pudiera salir impune.',
    'Algunos miembros de mi familia dicen que soy egoísta y que sólo pienso en mí.',
    'En el último año he cruzado el Atlántico en avión 30 veces.',
    'Beber alcohol me ayuda cuando me siento deprimido.',
    'Preferiría seguir a alguien antes que ser yo el líder.',
    'A menudo me vienen ideas a la mente mucho más rápido de lo que puedo expresarlas.',
    'A menudo me siento tan mal que quiero hacerme daño de verdad.',
    'Algunas personas dicen que soy extraño o raro.',
    'A veces encuentro consuelo en mi sufrimiento.',
    'A menudo creo que me han tratado injustamente.',
    'Muestro mi enfado rápidamente a las personas que no están de acuerdo conmigo.',
    'Casi siempre me siento culpable sin ninguna razón aparente.',
    'Desde hace algún tiempo me siento triste y deprimido y parece que no consigo animarme.',
    'Sé cómo seducir a la gente.',
    'Siempre he tenido que estar atento a la gente que intenta engañarme.',
    'Siempre estoy dispuesto a aceptar lo que a los demás les gustaría hacer.',
    'Afronto todos los retos de la vida con una actitud valiente y enérgica.',
    'Nunca siento que tenga algo interesante que aportar a una conversación.',
    'Si un medicamento no me hace efecto, es probable que lo tome con más frecuencia o aumente la dosis.',
    'En muchos periodos de mi vida he estado tan animado y he consumido tanta energía que luego me he sentido muy bajo de ánimo.',
    'A menudo me siento muy infeliz conmigo mismo.',
    'No me gusta cambiar mi rutina.',
    'No necesito tener amigos íntimos como tienen los demás.',
    'A veces me ha reconfortado herirme físicamente.',
    'Mucha gente ha estado espiando mi vida privada durante años.',
    'Cuando quiero, se me da bastante bien engañar a la gente.',
    'Incluso cuando las cosas van bien, creo que pronto irán mal.',
    'Se me da muy bien animar y motivar a los demás.',
    'Estoy dispuesto a pasar hambre para estar aún más delgado de lo que estoy.',
    'A menudo estoy irritable y de mal humor.',
    'Siempre intento acabar mi trabajo antes de dedicar tiempo a actividades de ocio.',
    'Solo las personas excepcionales pueden comprender mis capacidades.',
    'Realmente no entiendo los sentimientos humanos como los entienden los demás.',
    'Demasiadas normas impiden que haga lo que quiero.',
    'A veces siento que merezco ser infeliz.',
    'He estado abatido y triste gran parte de mi vida.',
    'Tiendo a estar de acuerdo con las opiniones de los demás.',
    'Evito la mayoría de las situaciones sociales porque creo que la gente me rechazará.'
  ];

  global.MCMI_ITEMS = ITEMS;
})(window);
